### ISSUE TITLE
Issues dataset CLEVRER loading annotations

### ISSUE THREAD

**Issue by alexcbb** [pairlab/SlotFormer#10]
Hello, first of all thank you for your very interesting work.

As I was doing some experiments with your repo, I found out some issues with annotations in the CLEVRER dataset for the slot training with masks (--load_mask == True). I instead added some script to evaluate some metrics during the learning of the vision model with mask quality, etc.
Two of the videos contains only 104 frames (the 9777 and 7648) and were failing in the _read_mask function. It seems that you already removed one "broken_video" in the _get_files function, was it related to the same kind of issue ? 

Next to that, I also had some issue related to the bbox loading: two other videos (8182 and 18700) seemed to have 8 objects in at least one of their frames and thus the bbox padding function was also failing.

Did you encounter this during your process or not at all, if yes did how did you solve the issue ? (for now I just added a list of broken_videos, 5 in total)

Thank you in advance.

**Comment by Wuziyi616** [comment]
Hi, I don't really remember the details but IIRC, indeed there are some files corrupted and I handled one of them in the code (as you pointed out). Then, I realized there might be more such files, and it's impossible to go over all videos to find them out (because there might be different errors, e.g., number of frames, number of objects, or just file corruptions). Therefore, I decided to just skip all wrong data when encountered. That's what my `_rand_another()` function is doing -- every time when an error occurs in the reading function, I'll just read another data item at a random index.

**Comment by alexcbb** [comment]
Ok, thank you for your answer, on my side it seems that the function was not correctly called in certain case as the try catch was only caught for ValueError, with a simple modification it seems to be working gently.

**Comment by Wuziyi616** [comment]
Ah that's true... I don't think I encountered issues other than a `ValueError` tho. Could it be that some data are corrupted during downloading? Also, I save videos as individual frames to speed up data loading, maybe that also causes different logic in the code. Anyways, I believe it should be fine just skip them.
